version: '3'
services:
  db:
    image: mysql:5.7.29
    container_name: e-shop-db
    ports:
      - '13306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default
      MYSQL_USER: default
      MYSQL_PASSWORD: secret
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  backend:
    build: ./backend/
    container_name: e-shop-backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/e-shop
    ports:
      - "13000:3000"
    depends_on:
      - db
  frontend:
    build: ./frontend/
    container_name: e-shop-frontend
    volumes:
      - ./frontend:/usr/src/app
    command: sh -c "cd e-shop && yarn start"
    ports:
      - "13030:3000"
